habitat_scene_dir: "/home/ws/dataset/HM3D_enviroment/v1/tasks/mp3d"
vlmaps_data_dir: "/home/ws/dataset/HM3D_enviroment/vlmaps_dataset"
# vlmaps_data_dir: "/home/ws/dataset/HM3D_enviroment/lvlmaps_dataset"