gml4cat = [
    "void",
    "wall",
    "gray cabinet",
    "red cabinet",
    "Beige cabinet",
    "light brown cabinet",
    "Beige door",
    "light brown door",
    "fire extinguisher",
    "window",
    "light gray floor",
    "ceiling",
    "officeChair",
    "cartons",
    "cart",
    "table",
    "stairs",
    "blue trolley",
    "water cooler",
    "objects",
]
